version: '3.9'

services:
    php-fpm:
        container_name: sytatsu-php-fpm
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${SAIL_APP_PORT:-80}:80'
            - '${SAIL_VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
#        networks:
#            - sytatsu_bridge
#        depends_on:
#            - mysql

    mysql:
        container_name: sytatsu-mysql
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${SAIL_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'data-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sytatsu_bridge
        healthcheck:
            test: 'CMD mysqladmin ping -p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    mailpit:
        container_name: sytatsu-mailpit
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sytatsu_bridge

networks:
    sytatsu_bridge:
        name: sytatsu-bridge
        driver: bridge

volumes:
    data-mysql:
        driver: local
